#:import ChatGptScreen screens.chat_gpt
#:import Message widgets.Message


<Message>:
    canvas:
        Color:
            rgba: root.md_bg_color
        Triangle:
            points: root.triangle_points

    MDLabel:
        text: root.message
        padding: [dp(10), dp(10), dp(5), dp(10)]

    MDLabel:
        text: root.time
        theme_font_size: 'Custom'
        font_size: sp(10)
        bold: True
        padding: [0, 0, dp(10), dp(5)]
        adaptive_size: True
        pos_hint: {'bottom': 1, 'right': 1}

    Image:
        source: root.image_path
        fit_mode: 'cover'
        anim_delay: 0
        mipmap: True



<ChatGptScreen>:
    name: 'chat_gpt_screen'

    prompt: send_field.text

    MDRelativeLayout:
        id: main_layout

        MDBoxLayout:
            orientation: 'vertical'
            md_bg_color: app.theme_cls.secondaryColor

            MDTopAppBar:
                type: 'small'
                theme_bg_color: 'Primary'

                MDTopAppBarLeadingButtonContainer:

                    MDActionTopAppBarButton:
                        icon: 'arrow-left-bold'
                        theme_icon_color: 'Custom'
                        icon_color: self.theme_cls.primaryColor
                        ripple_effect: False
                        focus_behavior: False
                        on_release:
                            app.back(screen='main_screen')

                MDTopAppBarTitle:
                    text: 'chat gpt'
                    theme_font_name: "Custom"
                    font_name: 'Hacked'

            MDRecycleView:
                id: chat_gpt
                do_scroll_y: False if chat_gpt_box.height < self.height else True
                scroll_y: 0
                effect_cls: ScrollEffect
                viewclass: 'Message'

                RecycleBoxLayout:
                    id: chat_gpt_box
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: dp(10)
                    padding: dp(10)

            MDBoxLayout:
                orientation: 'horizontal'
                adaptive_height: True
                padding: dp(10), 0, 0, 0
                md_bg_color: app.theme_cls.backgroundColor

                TextInput:
                    id: send_field
                    font_size: sp(18)
                    unfocus_on_touch: False
                    multiline: True
                    auto_indent: True
                    size_hint_y: None
                    height: self.minimum_height if self.minimum_height <= dp(100) else dp(100)
                    background_color: 1, 1, 1, 0
                    foreground_color: 'white'
                    disabled_foreground_color: 'white'
                    hint_text: 'message'
                    hint_text_color: 'gray'
                    cursor_color: app.theme_cls.primaryColor
                    cursor_width: dp(2)
                    pos_hint: {'center_y': .5}

                MDIconButton:
                    id: send_button
                    icon: 'send'
                    style: 'standard'
                    theme_icon_size: 'Custom'
                    icon_size: dp(25)
                    ripple_effect: False
                    focus_behavior: False
                    on_release:
                        root.send()
                        send_field.text = ''
