#:import ChatGptScreen screens

<ChatGptScreen>
    name: 'chat_gpt_screen'

    prompt: send_field.text

    MDFloatLayout:

        MDBoxLayout:
            orientation: 'vertical'
            md_bg_color: '#71b4f2'

            MyTopAppBar:
                id: chat_gpt_top_bar
                type_height: 'small'
                title: 'chat gpt'
                anchor_title: 'left'
                md_bg_color: root.md_bg_color
                left_action_items: [['assets/img/back_arrow_icon.png', lambda x: app.back(screen='main_screen')]]
                elevation: 0

            MDRecycleView:
                id: chat_gpt
                do_scroll_y: False if chat_gpt_box.height < self.height else True
                scroll_y: 0
                effect_cls: ScrollEffect
                viewclass: 'Message'

                RecycleBoxLayout:
                    id: chat_gpt_box
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: dp(10)
                    padding: dp(10)

            MDBoxLayout:
                orientation: 'horizontal'
                adaptive_height: True
                padding: dp(10), 0, 0, 0
                md_bg_color: root.md_bg_color

                TextInput:
                    id: send_field
                    multiline: True
                    auto_indent: True
                    size_hint_y: None
                    height: self.minimum_height if self.minimum_height <= dp(100) else dp(100)
                    background_color: 1, 1, 1, 0
                    foreground_color: 'white'
                    disabled_foreground_color: 'white'
                    hint_text: 'message'
                    hint_text_color: 'white'
                    cursor_color: 'white'
                    cursor_width: dp(2)
                    pos_hint: {'center_y': .5}

                MyIconButton:
                    icon: "send"
                    icon_size: dp(25)

                    on_release:
                        root.send()
                        send_field.text = ''