#:import ChatGptScreen main.screen

<ChatGptScreen>
    name: 'chat_gpt_screen'

    core: app
    prompt: send_field.text

    MDFloatLayout:

        MDBoxLayout:
            orientation: 'vertical'

            MDTopAppBar:
                id: chat_gpt_top_bar
                type_height: 'small'
                md_bg_color: root.md_bg_color
                left_action_items: [['arrow-left', lambda x: app.back(screen='main_screen')]]
                elevation: 0

            RecycleView:
                id: chat_gpt
                do_scroll_y: False if chat_gpt_box.height < self.height else True
                scroll_y: 0
                effect_cls: ScrollEffect
                viewclass: 'Message'

                canvas.before:
                    Color:
                        rgba: (.2, .5, .7, 1)
                    Rectangle:
                        size: self.size
                        pos: self.pos

                RecycleBoxLayout:
                    id: chat_gpt_box
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: dp(10)
                    padding: dp(10)

            MDBoxLayout:
                orientation: 'horizontal'
                adaptive_height: True
                padding: dp(10), 0, 0, 0
                md_bg_color: root.md_bg_color

                TextInput:
                    id: send_field
                    multiline: True
                    auto_indent: True
                    size_hint_y: None
                    height: self.minimum_height if self.minimum_height <= dp(100) else dp(100)
                    background_color: 1, 1, 1, 0
                    foreground_color: 'blue'
                    disabled_foreground_color: 'blue'
                    hint_text: 'message'
                    hint_text_color: 'blue'
                    cursor_color: 'blue'
                    cursor_width: dp(2)
                    pos_hint: {'center_y': .5}

                MDIconButton:
                    icon: "send"
                    size_hint_y: None
                    icon_size: dp(25)

                    on_release:
                        root.send()
                        send_field.text = ''
