<ChatGptScreen>
    name: 'chat_gpt_screen'

    core: app
    prompt: send_field.text

    MDFloatLayout:

        MDBoxLayout:
            orientation: 'vertical'
            padding: 0, 0, 0, 15

            MDTopAppBar:
                id: chat_gpt_top_bar
                specific_text_color: 'gray'
                type_height: 'small'
                md_bg_color: app.theme_cls.bg_dark
                left_action_items: [['arrow-left', lambda x: app.back(screen='main_screen')]]
                elevation: 0

            MDRecycleView:
                id: chat_gpt
                viewclass: 'Message'
                effect_cls: ScrollEffect
                scroll_y: 0

                canvas.before:
                    Color:
                        rgba: (.2, .5, .7, 1)
                    Rectangle:
                        size: self.size
                        pos: self.pos

                RecycleBoxLayout:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 10
                    padding: 10, 10, 10, 10

            MDRelativeLayout:
                id: send_box
                size_hint: .7, None
                height: send_field.height
                pos_hint: {'center_x': .5}

                MDTextField:
                    id: send_field
                    mode: 'round'
                    hint_text: 'Write message...'


                MDIconButton:
                    icon: "send"
                    pos_hint: {"center_y": .5}
                    pos: send_field.width - self.width, 0
                    on_release:
                        root.send()
                        send_field.text = ''
