<ChatGptScreen>
    name: 'chat_gpt_screen'

    core: app
    prompt: send_field.text

    MDFloatLayout:

        MDBoxLayout:
            orientation: 'vertical'

            MDTopAppBar:
                id: chat_gpt_top_bar
                specific_text_color: 'gray'
                type_height: 'small'
                md_bg_color: app.theme_cls.bg_dark
                left_action_items: [['arrow-left', lambda x: app.back(screen='main_screen')]]
                elevation: 0

            RecycleView:
                id: chat_gpt
                do_scroll_y: False if chat_gpt_box.height < self.height else True
                scroll_y: 0
                effect_cls: ScrollEffect
                viewclass: 'Message'

                canvas.before:
                    Color:
                        rgba: (.2, .5, .7, 1)
                    Rectangle:
                        size: self.size
                        pos: self.pos

                RecycleBoxLayout:
                    id: chat_gpt_box
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 10
                    padding: 10, 10, 10, 10

            MDBoxLayout:
                orientation: 'horizontal'
                adaptive_height: True
                padding: 10, 0, 0, 0

                canvas:
                    Color:
                        rgba: .3, .3, .9, 1
                    Rectangle:
                        size: self.size
                        pos: self.pos

                TextInput:
                    id: send_field
                    multiline: True
                    auto_indent: True
                    size_hint_y: None
                    height: self.minimum_height if self.minimum_height <= 100 else 100
                    background_color: 1, 1, 1, 0
                    foreground_color: 'white'
                    disabled_foreground_color: 'white'
                    hint_text: 'message'
                    hint_text_color: 'white'
                    cursor_color: 'white'
                    cursor_width: 2
                    focus: True
                    unfocus_on_touch: False
                    pos_hint: {'center_y': .5}

                MDIconButton:
                    icon: "send"
                    size_hint_y: None
                    icon_size: 25

                    on_release:
                        root.send()
                        send_field.text = ''
